src/pydjjpro/urls.py
from django.conf.urls import url
from django.contrib import admin
from pydjjapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', views.index, name='index'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^success/$', views.success, name='success')
]

src/pydjjapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Feedbaack(models.Model):
    contact_name = models.CharField(max_length=30, blank=False)
    contact_email = models.EmailField(unique=True)
    content = models.CharField(blank=False, max_length=500)
    ip_add = models.CharField(max_length=120, default='ABC')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.contact_email

    def get_absolute_url(self):
        return reverse('success')

src/pydjjapp/forms.py
from django import forms
from .models import Feedbaack
# our new form

class ContactForm(forms.ModelForm):
    content = forms.CharField( widget=forms.Textarea )
    class Meta:
        model = Feedbaack
        fields = '__all__'
        # fields = ["contact_name", "contact_email", "content",]
        # exclude = ['ip_add']s

src/pydjjapp/views.py
from __future__ import unicode_literals
from django.core.mail import EmailMessage
from django.shortcuts import render
from django.shortcuts import redirect, HttpResponseRedirect
from django.template import Context
from django.template.loader import get_template
from .forms import ContactForm
from .models import Feedbaack
from django.core.urlresolvers import reverse

def index(request):
    return render(request, 'pydjjapp/index.html', {})


def success(request):
    return render(request, 'pydjjapp/commentsucc.html', {})


def get_ip(request):
    try:
        x_forward = request.META.get("HTML_X_FORWARDED_FOR")
        if x_forward:
            ip = x_forward.split(",")[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
    except:
        ip = ""
    return ip

def contact(request):
    print(request.META.get('REMOTE_ADDR'))
    form = ContactForm(request.POST or None)
    if form.is_valid():
        new_sub = form.save(commit=False)
        contact_name = form.cleaned_data['contact_name']
        contact_email = form.cleaned_data['contact_email']
        content = form.cleaned_data['content']
        new_old, created = Feedbaack.objects.get_or_create(contact_name=contact_name,contact_email=contact_email,content=content)
        if created:
            new_old.ip_add = get_ip(request)
            new_old.save()
            return HttpResponseRedirect(reverse('success'))
        
        # contact_name = request.POST.get('contact_name', '')
        # contact_email = request.POST.get('contact_email', '')
        # form_content = request.POST.get('content', '')
        # template = get_template('contact_temp.txt')

        # context = {
        #     'contact_name': contact_name,
        #     'contact_email': contact_email,
        #     'form_content': form_content,
        # }
        # content = template.render(context)

        # email = EmailMessage(
        #     "New contact form submission",
        #     content,
        #     "pydj" +'',
        #     ['ronbaddi004@gmail.com'],
        #     headers = {'Reply-To': contact_email }
        # )

        # email.send()
        # return redirect('contact')

    return render(request, 'pydjjapp/contactUs.html', {
        'form': form,
    })

src/templates/pydjjapp/base.html
{% load static %}
<html>
    <head>
        <title>
            {% block title %}
            PYDJ
            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">AYRO</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{% url 'index' %}">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'contact' %}">Contact Us</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="admin/">Admin</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
        <div class="container">
            {% block content %}

            {% endblock %}
        </div>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    </body>
</html>

src/templates/pydjjapp/commentsucc.html
{% extends 'pydjjapp/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<div class="jumbotron">
    <h2 style="text-align:center;">Successfully Commented!</h2>
    <p style="text-align:center;">Thank You. For Submitting your Feedback.</p>
</div>
{% endblock %}

src/templates/pydjjapp/contactUs.html
{% extends 'pydjjapp/base.html' %}
{% block title %}
Contact
{% endblock %}

{% block content %}
<div class="jumbotron">
<h1>Contact</h1>    
<form action="" method="post">
{% csrf_token %}
    <!-- {{ form.as_p}} -->
    <p>
        <label for="id_contact_name">Name:</label>
        <input type="text" name="contact_name" id="id_contact_name" maxlength="30" />
    </p>
    <p>
        <label for="id_contact_email">Email:</label>
        <input type="text" name="contact_email" id="id_contact_email" maxlength="50" />
    </p>
    <p>
        <label for="id_content">Content:</label>
        <textarea type="text" name="content" id="id_content" rows="10" cols="40"></textarea>
    </p>
    <p style="visibility:hidden;">
        <label for="id_ip_add">Ip add:</label>
        <input type="hidden" name="ip_add" value="ABC" required id="id_ip_add" maxlength="120" />
    </p>
    <button class="btn btn-lg btn-primary" type="submit">Send</button>
</form>
</div>
{% endblock %}

src/templates/pydjjapp/index.html
{% extends 'pydjjapp/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="jumbotron">
<h1>Welcome</h1>
</div>
{% endblock %}